version: "3"

services:
  hapi-fhir-jpaserver-start:
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    environment:
      HAPI_FHIR_URL_PUBLIC: ${HAPI_FHIR_URL_PUBLIC}
      HAPI_DB_URL: ${HAPI_DB_URL}
      HAPI_DB_USER: ${HAPI_DB_USER}
      HAPI_DB_PASS: ${HAPI_DB_PASS}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6060:6080
